"use strict";
exports.__esModule = true;
exports.REGEX_MATCH_POINTER = /#\w+/gi;
exports.REGEX_MATCH_COMMAND = /@\w+(?!\S)/gi;
exports.REGEX_MATCH_PARENT = /\^\w+/gi;
exports.REGEX_HAS_ARGS = /\((.+?)\)/gi;
exports.REGEX_MATCH_TYPE_HAS_ARGS = /(@|#|\^|&)\w+\((.+?)\)(?!\S)/gi;
exports.REGEX_MATCH_TYPE = /(@|#|\^|&)\w+(?!\S)/gi;
exports.REGEX_PULL_NAME = /(@|#|\^|&)\w+/gi;
exports.REGEX_START_BRACKET = '(';
exports.REGEX_COMMA = ',';
exports.REGEX_ARGS_CONTENT = /(\(|\)|\'|\")/gi;
exports.REGEX_MATCH_NUMBER_ONLY = /^[0-9]+$/gi;
exports.REGEX_SUBCOMMANDS = /(#\w+|@\w+|^\w+)/gi;
